### ISSUE TITLE
Task 4 - Request your public certificate from DigiCert

### ISSUE THREAD

**Issue by hbunkradt** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#22]
# Module: 00
#### Step: 1

Description of issue
The created certificate request for Digicert certreq-lab<customlabnumber>.o365ready.com.txt is wrong,because the FQDN contains capital letter and this is not allowed by Digicert.
Repro steps:
![image](https://user-images.githubusercontent.com/24456014/151583686-0b934146-8ba7-4dd8-bf9c-f35ee2b71237.png)

**Comment by dahans-msft2** [comment]
Hi @hbunkradt, this issue was fixed in the newest set of lab VM's with a new version of the CallandMeetLabs.exe script.  Can you verify that you're using the newest VM's and the version of CallandMeetLabs.exe is 7.2.1?

![image](https://user-images.githubusercontent.com/49003767/151600640-d9dccff5-a948-4379-b032-ba4c232a29eb.png)

**Comment by hbunkradt** [comment]
Ok, on extremelabs it works fine, on godeploy I had the version 6.2.1.0. My temprary fix was to change the fqdn complete to small letter.

**Comment by dahans-msft2** [comment]
Will talk with godeploy about getting their VM's updated with the new versions.  Thanks @hbunkradt, I'll go ahead and close this issue.
