### ISSUE TITLE
Lab: 03 Expand your Teams Voice Environment to use Direct Routing

### ISSUE THREAD

**Issue by hbunkradt** [MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer#23]
# Module: Expand your Teams Voice Environment to use Direct Routing
#### Step: 19

The public IP will be added to the DNS server on RRAS, but the old IP address still exist on the DNS server and should be removed from DNS before adding a ne IP for the SBC.

#### Step: 2

Teams-TLSContext has to be created. These context does not exist

#### Step: 1

Silk-WB with a pay lode type of 103, the Payload Type is 104 in Teams!

#### Step: 9

Source IP Group Sip Trunk does not exist and also the configuration for the 3CXphone is complete missed. I have add my Audiocodes config from my working Lab. Also the IP on the 3CXPhone has to change to the public IP of the Audiocodes SBC.
![image](https://user-images.githubusercontent.com/24456014/151586542-7e50e0d6-3916-469d-9c4c-97eea80cfbd9.png)
[MS720-AC-Board_lab.txt](https://github.com/MicrosoftLearning/MS-720-Microsoft-Teams-Voice-Engineer/files/7960317/MS720-AC-Board_lab.txt)

**Comment by dahans-msft2** [comment]
Hi @hbunkradt,

All of these issues, minus the 3CX softphone configuration, were fixed.  We unfortunately have to remove the Task around SBC Logs and the softphone due to 3rd party software licensing issues.  We will revisit this task and try to resolve those issues in the future.  Thank you for submitting these issues.  They'll be resolved in the next PR.
